CREATE DATABASE PROYECTO_BANCO_NODE
USE PROYECTO_BANCO_NODE

--- CREACION TABLA
CREATE TABLE ASIGNATURA(
ID INT IDENTITY (1,1) ,
CODIGO VARCHAR (30) PRIMARY KEY,
NOMBRE VARCHAR(30),
CREDITOS TINYINT

)
GO
CREATE TABLE ESTUDIANTES(
ID INT IDENTITY (1,1) ,
CODIGO VARCHAR (30) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (30)NOT NULL,
APELLIDOS VARCHAR(30) NOT NULL,
SEMESTRE VARCHAR(30) NOT NULL,
CARRERA VARCHAR(30) NOT NULL,
CODASIGNATURA VARCHAR(30) 
CONSTRAINT FK_ESTUDIANTES_01 FOREIGN KEY REFERENCES ASIGNATURA(CODIGO)
ON UPDATE CASCADE
)
GO
CREATE TABLE DOCENTES(
ID  INT IDENTITY(1,1),
CODIGO VARCHAR (30)  PRIMARY KEY ,
NOMBRE VARCHAR (30) NOT NULL,
APELLIDOS VARCHAR(30)NOT NULL,
CODIGOASIGNATURA VARCHAR(30)
CONSTRAINT FK_DOCENTES_01 FOREIGN KEY REFERENCES ASIGNATURA(CODIGO)
ON UPDATE CASCADE
)
GO
CREATE TABLE RECORD_ACADEMICO(
ID INT IDENTITY (1,1),
CODIGO VARCHAR (30) NOT NULL,
FECHA DATE DEFAULT GETDATE() ,
PERIODO VARCHAR (30) NOT NULL,
COESTUDIANTE VARCHAR (30)
CONSTRAINT FK_RECORDACADEMICO_01 FOREIGN KEY REFERENCES ESTUDIANTES(CODIGO)
ON UPDATE CASCADE,
CODOCENTE VARCHAR(30)
CONSTRAINT FK_RECORDACADEMICO_02 FOREIGN KEY REFERENCES DOCENTES(CODIGO),
NOTA1 DECIMAL(5,2),
NOTA2 DECIMAL(5,2),
PROMEDIO AS (NOTA1 + NOTA2)/2,

)


--- INSERTAR ASIGNATURA
CREATE PROC INSERTAR_ASIGNATURA(
@CODIGO VARCHAR(30),
@NOMBRE VARCHAR(30),
@CREDITOS TINYINT
)
AS
    BEGIN
        INSERT INTO ASIGNATURA(CODIGO, NOMBRE,CREDITOS)
        VALUES(@CODIGO, @NOMBRE, @CREDITOS)
    END

EXEC INSERTAR_ASIGNATURA 'AS2','BIOLOGIA',3


--- INSERTAR ESTUDIANTES
CREATE PROC INSERTAR_ESTUDIANTES(
@CODIGO VARCHAR(30),
@NOMBRE VARCHAR(30),
@APELLIDOS VARCHAR(30),
@SEMESTRE VARCHAR(30),
@CARRERA VARCHAR(30),
@CODASIGNATURA VARCHAR(30)
)
AS
    BEGIN
        INSERT INTO ESTUDIANTES(CODIGO, NOMBRE,APELLIDOS,SEMESTRE,CARRERA,CODASIGNATURA)
        VALUES(@CODIGO, @NOMBRE, @APELLIDOS,@SEMESTRE,@CARRERA,@CODASIGNATURA)
    END

EXEC INSERTAR_ESTUDIANTES 'ES1','ANDRES','MONTIEL','2SEMESTRE','SISTEMAS','AS1'


--- INSERTAR DOCENTES
CREATE PROC INSERTAR_DOCENTES(
@CODIGO VARCHAR(30),
@NOMBRE VARCHAR(30),
@APELLIDOS VARCHAR(30),
@CODIGOASIGNATURA VARCHAR(30)
)
AS
    BEGIN
        INSERT INTO DOCENTES(CODIGO, NOMBRE,APELLIDOS,CODIGOASIGNATURA)
        VALUES(@CODIGO, @NOMBRE, @APELLIDOS,@CODIGOASIGNATURA)
    END

EXEC INSERTAR_DOCENTES 'DO1','RICARDO','MONTES','AS1'

--- INSERTAR RECORD_ACADEMICO
CREATE PROC INSERTAR_REACADEMICO(
@CODIGO VARCHAR(30),
@PERIODO VARCHAR(30),
@COESTUDIANTE VARCHAR(30),
@CODOCENTE VARCHAR(30),
@NOTA1 DECIMAL,
@NOTA2 DECIMAL
)
AS
    BEGIN
        INSERT INTO RECORD_ACADEMICO(CODIGO, PERIODO,COESTUDIANTE,CODOCENTE,NOTA1,NOTA2)
        VALUES(@CODIGO, @PERIODO, @COESTUDIANTE,@CODOCENTE,@NOTA1,@NOTA2)
    END

EXEC INSERTAR_REACADEMICO 'RE1','CORTE1','ES1','DO1',3.5,4.5